### ISSUE TITLE
what initial state should be sent, if we are not sending *all* the state

### ISSUE THREAD

**Issue by christopherreay** [coalition-of-invisible-colleges/ao-react#5]
So the UI expects there to be a "Community Hub" card in the card database, as well as really the card for the currently logged in user.

I dont know if anything more than this is strictly required. 

It would clearly be useful to load all cards that are directly connected to either the Community Hub card or the current Member card along with that state. Should be ok?

**Comment by andersaamodt** [comment]
Yes, this sounds right. There is a crawler I just updated in calculations.js. It now also correctly crawls the grid on each card.
