### ISSUE TITLE
This new connection callback does not appear to correctly follow the response of the insertEvent function

### ISSUE THREAD

**Issue by christopherreay** [coalition-of-invisible-colleges/ao-react#6]
https://github.com/coalition-of-invisible-colleges/ao-react/blob/4cdce6716fd9f53c147f4ec55fac9bd8cd463639/manage/connect.js#L107
The expected callback signature is `(event, result) =>`

https://github.com/coalition-of-invisible-colleges/ao-react/blob/789f2ea8e59e9062e631198377c9465c1fad6700/src/server/dctrlDb.js#L125
the actual callback signature is `(error, { event: event, result: result})`

@andersaamodt

**Comment by andersaamodt** [comment]
Fixed in connect.js, will test & commit later today thanks!
